#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N bmm_lr_learning-rate_0.0020.00040.00008_2
#$ -o ./logs/output_bmm_lr_bmm_lr_learning-rate_0.0020.00040.00008_2.txt
#$ -e ./logs/error_bmm_lr_bmm_lr_learning-rate_0.0020.00040.00008_2.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate "0.002,0.0004,0.00008" --random-seed 8627169
