#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N bmm_lr_learning-rate_0.0010.00020.00004_1
#$ -o ./logs/output_bmm_lr_bmm_lr_learning-rate_0.0010.00020.00004_1.txt
#$ -e ./logs/error_bmm_lr_bmm_lr_learning-rate_0.0010.00020.00004_1.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate "0.001,0.0002,0.00004" --random-seed 235899598
