#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N bmm_lr_learning-rate_0.00050.00010.00002_0
#$ -o ./logs/output_bmm_lr_bmm_lr_learning-rate_0.00050.00010.00002_0.txt
#$ -e ./logs/error_bmm_lr_bmm_lr_learning-rate_0.00050.00010.00002_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate "0.0005,0.0001,0.00002" --random-seed 193012823
