#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N digital6_M0hidden_114_0
#$ -o ./logs/output_digital6_digital6_M0hidden_114_0.txt
#$ -e ./logs/error_digital6_digital6_M0hidden_114_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --hidden "114" --random-seed 193012823 --max-w 1 --method 0 --batch-size 100 --quant-actNM 6 --quant-actMVM 6 --quant-inp 6 --quant-w 6
