#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N digital_M0quant-actNM_2_1
#$ -o ./logs/output_digital_digital_M0quant-actNM_2_1.txt
#$ -e ./logs/error_digital_digital_M0quant-actNM_2_1.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --quant-actNM "2" --random-seed 235899598 --noise-injectionT 0 --noise-injectionI 0  --max-w 1 --rows-bias 100 --method 0 --quant-actMVM 2 --quant-inp 2 --quant-w 2
