#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N digital_M1quant-actNM_12_0
#$ -o ./logs/output_digital_digital_M1quant-actNM_12_0.txt
#$ -e ./logs/error_digital_digital_M1quant-actNM_12_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --quant-actNM "12" --random-seed 193012823 --noise-injectionT 0 --noise-injectionI 0  --max-w 1 --rows-bias 100 --method 1 --quant-actMVM 12 --quant-inp 12 --quant-w 12
