#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N lr_bmm_learning-rate_"0.001,0.0002,0.00004"_0
#$ -o ./logs/output_lr_bmm_lr_bmm_learning-rate_"0.001,0.0002,0.00004"_0.txt
#$ -e ./logs/error_lr_bmm_lr_bmm_learning-rate_"0.001,0.0002,0.00004"_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate "0.001,0.0002,0.00004" --random-seed 193012823