#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N lr_bmm_learning-rate_"0.002,0.0004,0.00008"_1
#$ -o ./logs/output_lr_bmm_lr_bmm_learning-rate_"0.002,0.0004,0.00008"_1.txt
#$ -e ./logs/error_lr_bmm_lr_bmm_learning-rate_"0.002,0.0004,0.00008"_1.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate "0.002,0.0004,0.00008" --random-seed 235899598