#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N lr_sweep_learning-rate_0.0005,0.0001,0.00002_2
#$ -o ./logs/output_lr_sweep_lr_sweep_learning-rate_0.0005,0.0001,0.00002_2.txt
#$ -e ./logs/error_lr_sweep_lr_sweep_learning-rate_0.0005,0.0001,0.00002_2.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate 0.0005,0.0001,0.00002 --random-seed 8627169
