#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N lr_sweep_learning-rate_0.01,0.005,0.001_1
#$ -o ./logs/output_lr_sweep_lr_sweep_learning-rate_0.01,0.005,0.001_1.txt
#$ -e ./logs/error_lr_sweep_lr_sweep_learning-rate_0.01,0.005,0.001_1.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python KWS_LSTM.py --learning-rate 0.01,0.005,0.001 --random-seed 235899598
