#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N Quiwen_SWA_checkpoint_5de899ec-a086-4025-b44d-54944b2e576f_0
#$ -o ./logs/output_Quiwen_SWA_Quiwen_SWA_checkpoint_5de899ec-a086-4025-b44d-54944b2e576f_0.txt
#$ -e ./logs/error_Quiwen_SWA_Quiwen_SWA_checkpoint_5de899ec-a086-4025-b44d-54944b2e576f_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python swa.py --checkpoint 5de899ec-a086-4025-b44d-54944b2e576f --random-seed 193012823
