#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N SWA_checkpoint_2fc3aec6-b7e3-4deb-baf9-5857c31fa0ac_0
#$ -o ./logs/output_SWA_SWA_checkpoint_2fc3aec6-b7e3-4deb-baf9-5857c31fa0ac_0.txt
#$ -e ./logs/error_SWA_SWA_checkpoint_2fc3aec6-b7e3-4deb-baf9-5857c31fa0ac_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python swa.py --checkpoint 2fc3aec6-b7e3-4deb-baf9-5857c31fa0ac --random-seed 193012823
