#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N SWA_checkpoint_ea886fba-b40f-4a23-afea-f4bd113ab667_1
#$ -o ./logs/output_SWA_SWA_checkpoint_ea886fba-b40f-4a23-afea-f4bd113ab667_1.txt
#$ -e ./logs/error_SWA_SWA_checkpoint_ea886fba-b40f-4a23-afea-f4bd113ab667_1.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python swa.py --checkpoint ea886fba-b40f-4a23-afea-f4bd113ab667 --random-seed 235899598
